name: Generate ASCII Artwork The Goat

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
          
        - name: Install Cowsay program
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay CMD
          run: cowsay -f goat "Run for cover, I am a GOAT....Maahaaa" >> goat.txt

        - name: Test File Exists
          run: grep -i "goat" goat.txt
          
        - name: Read Files
          run: cat goat.txt

        - name: List Repo Files
          run: ls -ltra