name: Generate ASCII Artwork The tux

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
          
        - name: Install Cowsay program
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay CMD
          run: fortune | cowsay -f tux | lolcat "Run for cover, I am a GOAT....Maahaaa" >> tux.txt

        - name: Test File Exists
          run: grep -i "tux" tux.txt
          
        - name: Read Files
          run: cat tux.txt

        - name: List Repo Files
          run: ls -ltra