
name: Second workflow testing
on: push
env:
    CONTAINER_REGISTRY: dockerio
    CONTAINER_REGISTRY_USER_NAME: ravi
    CONTAINER_REGISTRY_USER_PASSWORD: password
    IMAGE_NAME: github-actions-nginx

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Basic commands
          run: |
            cat /etc/*release*
            cat /proc/version
            git --version
            sudo apt-get install cowsay -y
        - name: Execute Cowsay command
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
        - name: Upload dragon.txt file
          uses: actions/upload-artifact@v3
          with:
            name: dragon-txt-file
            path: dragon.txt

    second_job:
        runs-on: ubuntu-latest
        needs: first_job
        steps:
        - name: Git clone
          uses: actions/checkout@v4
        - name: List all content
          run: |
            ls -la *
            ls -l README.md
        - name: Download dragon.txt file
          uses: actions/download-artifact@v3
          with:
            name: dragon-txt-file
        - name: Show dragon.txt file
          run:  cat dragon.txt

    third_job:
        runs-on: ubuntu-latest
        needs: [first_job, second_job]
        steps:
        - name: Docker builds
          run: |
            echo docker build -t ${{ env.CONTAINER_REGISTRY}}/${DOCKER_USER_NAME}/${IMAGE_NAME}:latest .


