
name: Second workflow testing
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Basic commands
          run: |
            cat /etc/*release*
            cat /proc/version
            git --version
            sudo apt-get install cowsay -y

    second_job:
        runs-on: ubuntu-latest
        needs: first_job
        steps:
        - name: Git clone
          uses: actions/checkout@v4
        - name: List all content
          run: |
            ls -la *
            ls -l README.md
