
name: Third Workflow Testing
on:
  workflow_dispatch:
  #schedule:
  #  cron: 

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Basic commands
          run: |
            cat /etc/*release*
            cat /proc/version
            git --version
            sudo apt-get install cowsay -y
